export type Event = {
  id: string;
  title: string;
  description: string;
  date: string; // ISO date
  time: string; // HH:mm
  location: string;
  category: string;
  organization: string;
  capacity: number;
  ticketsIssued: number;
  image: string;
};

export const events: Event[] = [
  {
    id: "1",
    title: "Welcome Week Concert",
    description: "Kick off the semester with live music and food trucks.",
    date: "2025-09-12",
    time: "19:00",
    location: "Main Quad Stage",
    category: "Music",
    organization: "Student Union",
    capacity: 800,
    ticketsIssued: 620,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "2",
    title: "Tech Talk: AI on Campus",
    description: "A panel on how AI is transforming campus life.",
    date: "2025-09-18",
    time: "17:30",
    location: "Engineering Auditorium",
    category: "Talks",
    organization: "CompSci Society",
    capacity: 300,
    ticketsIssued: 280,
    image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "3",
    title: "Charity 5K Run",
    description: "Run or walk to raise funds for local shelters.",
    date: "2025-09-22",
    time: "08:00",
    location: "Riverside Trail",
    category: "Sports",
    organization: "Athletics Club",
    capacity: 400,
    ticketsIssued: 150,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "4",
    title: "Comedy Night",
    description: "Stand-up comedy featuring student performers and local comedians.",
    date: "2025-09-25",
    time: "20:00",
    location: "Student Center Theater",
    category: "Arts",
    organization: "Student Union",
    capacity: 200,
    ticketsIssued: 180,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "5",
    title: "Hackathon 2025",
    description: "48-hour coding competition with prizes and networking opportunities.",
    date: "2025-09-28",
    time: "09:00",
    location: "Computer Science Building",
    category: "Career",
    organization: "CompSci Society",
    capacity: 150,
    ticketsIssued: 120,
    image: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "6",
    title: "Open Mic Night",
    description: "Share your talents! Music, poetry, comedy, and more.",
    date: "2025-10-02",
    time: "19:30",
    location: "Campus Coffee House",
    category: "Arts",
    organization: "Drama Society",
    capacity: 80,
    ticketsIssued: 65,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "7",
    title: "Yoga in the Park",
    description: "Morning yoga session in the campus botanical garden.",
    date: "2025-10-05",
    time: "07:00",
    location: "Botanical Garden",
    category: "Sports",
    organization: "Wellness Club",
    capacity: 50,
    ticketsIssued: 35,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "8",
    title: "Career Fair",
    description: "Connect with top employers and explore internship opportunities.",
    date: "2025-10-08",
    time: "10:00",
    location: "Convention Center",
    category: "Career",
    organization: "Career Services",
    capacity: 1000,
    ticketsIssued: 850,
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "9",
    title: "Film Screening: Documentary Night",
    description: "Watch award-winning documentaries followed by discussion.",
    date: "2025-10-12",
    time: "18:00",
    location: "Media Arts Center",
    category: "Culture",
    organization: "Film Society",
    capacity: 120,
    ticketsIssued: 95,
    image: "https://images.unsplash.com/photo-1574267432553-4b4628081c31?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "10",
    title: "Charity Bake Sale",
    description: "Delicious homemade treats supporting local food bank.",
    date: "2025-10-15",
    time: "11:00",
    location: "Student Center Lobby",
    category: "Social",
    organization: "Volunteer Club",
    capacity: 200,
    ticketsIssued: 0,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "11",
    title: "Poetry Slam",
    description: "Express yourself through spoken word poetry.",
    date: "2025-10-18",
    time: "19:00",
    location: "Library Reading Room",
    category: "Arts",
    organization: "Literary Society",
    capacity: 100,
    ticketsIssued: 75,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1600&auto=format&fit=crop",
  },
  {
    id: "12",
    title: "Guest Lecture: Sustainability",
    description: "Learn about environmental initiatives and sustainable living.",
    date: "2025-10-22",
    time: "16:00",
    location: "Environmental Science Hall",
    category: "Talks",
    organization: "Environmental Club",
    capacity: 250,
    ticketsIssued: 200,
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1600&auto=format&fit=crop",
  },
];

export const categories = [
  "Music",
  "Talks",
  "Workshops",
  "Sports",
  "Arts",
  "Social",
  "Career",
  "Culture",
];


